# Description: Configuration file for the UNETR model
# Path to the data json file
# data: /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/data/monai_data/fake.json
data: /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/data/monai_data/dataset_2024-03-13_seed42_canproco.json
# Path to the output directory
output_dir : /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/results/
# Resampling resolution
pixdim : [0.6, 0.6, 0.6]
# Spatial size of the input data
spatial_size : [32, 208, 208]
batch_size : 16

# UNETR model parameters
feature_size : 8
hidden_size : 768
mlp_dim : 3072
num_heads : 12

# Optimizer parameters
lr : 0.0001
weight_decay: 0.00001
early_stopping_patience : 10

# Training parameters
max_iterations : 25000
eval_num : 10

# Model saving
best_model_path : /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/results/best_metric_model.pth

# log saving
log_path : /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/results/

# WANDB
experiment_name : monai_unet_canproco

seed : 42