"""
This file takes the .txt file generated by the download_data.sh script and creates a JSON file with the following structure:
{
    "data_path": "/path/to/data",
    "TRAINING": [
        {
            "image": "relative/path/to/image.nii.gz",
            "label": "dummy.nii.gz"
        },
        ...
    ],
    "VALIDATION": [
        {
            "image": "relative/path/to/image.nii.gz",
            "label": "dummy.nii.gz"
        },
        ...
    ],
    "TESTING": [
        {
            "image": "relative/path/to/image.nii.gz",
            "label": "dummy.nii.gz"
        },
        ...
    ]
}

Source: https://github.com/ivadomed/SpineFoundation/blob/main/data_management/create_files_json.py
"""

import json
import argparse
from pathlib import Path
import random


def load_file_paths(txt_file):
    with open(txt_file, "r") as f:
        paths = [line.strip() for line in f.readlines() if line.strip()]
    return paths


def split_files(data_path, paths, seed=42):
    """
    Random split into TRAINING / VALIDATION / TESTING
    80% / 10% / 10% with fixed seed for reproducibility.
    """
    random.seed(seed)
    paths = list(paths)  # ensure it's a list
    random.shuffle(paths)

    n_total = len(paths)
    n_train = int(0.8 * n_total)
    n_val = int(0.1 * n_total)
    n_test = n_total - n_train - n_val  # remainder

    training_paths = paths[:n_train]
    validation_paths = paths[n_train:n_train + n_val]
    testing_paths = paths[n_train + n_val:]

    def make_entries(file_list):
        entries = []
        for p in file_list:
            relative_path = str(Path(p).resolve()).replace(data_path + "/", "")
            entries.append({
                "image": relative_path,
                "label": "dummy.nii.gz"
            })
        return entries

    training = make_entries(training_paths)
    validation = make_entries(validation_paths)
    testing = make_entries(testing_paths)

    return training, validation, testing


def main(data_path, txt_file, output_file): 
    paths = load_file_paths(txt_file)
    training, validation, testing = split_files(data_path, paths, seed=42)

    output = {
        "data_path": data_path,
        "TRAINING": training,
        "VALIDATION": validation,
        "TESTING": testing
    }

    with open(output_file, "w") as f:
        json.dump(output, f, indent=4)

    print(f"JSON written to {output_file}")
    print(f"TRAINING: {len(training)} files")
    print(f"VALIDATION: {len(validation)} files")
    print(f"TESTING: {len(testing)} files")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create files JSON from text file.")
    parser.add_argument("--data_path", required=True, help="Path to data")
    parser.add_argument("--txt_file", required=True, help="Path to files.txt")
    parser.add_argument("--output_file", required=True, help="Output JSON file")
    args = parser.parse_args()

    main(args.data_path, args.txt_file, args.output_file)