# Description: Configuration file for the UNETR model
# Path to the data json file
# data: /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/data/monai_data/fake.json
# data: /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/data/monai_data/fake_lesion_sc.json
data: /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/data/monai_data/fake_10_each.json
# data: /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/data/monai_data/fake_sc.json
# data: /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/data/monai_data/dataset_2024-03-13_seed42_canproco.json
# Path to the output directory
output_dir : /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/results/
# Resampling resolution
# pixdim : [1.0, 1.0, 1.0]
pixdim : [0.7, 0.7, 0.7]
# pixdim : [0.5, 0.5, 0.5]
# Spatial size of the input data
spatial_size : [32, 128, 128] # RL, AP, IS
batch_size : 4

# UNETR model parameters
feature_size : 8
hidden_size : 768
mlp_dim : 3072
num_heads : 12

# Optimizer parameters
lr : 0.001
weight_decay: 0.00001
early_stopping_patience : 100

# Training parameters
max_iterations : 3000
eval_num : 2

# Model saving
best_model_path : /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/results/best_metric_model.pth

# log saving
log_path : /home/GRAMES.POLYMTL.CA/p119007/ms_lesion_agnostic/results/

# WANDB
experiment_name : monai_unet_canproco

seed : 42

# UNET model parameters
unet_channels : [32, 64, 128, 256, 512, 1024]
unet_strides : [2, 2, 2, 2, 2, 2, 2]

#Attention Unet
channels : [32, 64, 128, 256, 512]
strides : [2, 2, 2, 2, 2]